FROM debian

RUN apt-get update && \ 
    apt-get install -y --no-install-recommends \
    apache2 \
    curl && \ 
    apt-get clean && \
    apt-get autoremove && \
    apt-get autoclean
RUN chown www-data:www-data /var/lock && \
    chown www-data:www-data /var/run/ && \
    chown www-data:www-data /var/log/

ENV APACHE_LOCK_DIR="var/lock"
ENV APACHE_PID_FILE="/var/run/apache2.pid"
ENV APACHE_RUN_USER="www-data"
ENV APACHE_RUN_GROUP="www-data"
ENV APACHE_LOG_DIR="/var/log/apache2/"

ADD index.html /var/www/html/
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
  CMD [ "curl -f localhost || exit 1" ]
LABEL description="Webserver"
LABEL version="1.0.0"

USER root

WORKDIR /var/www/html/

VOLUME [ "/var/www/html/" ]
EXPOSE 80

ENTRYPOINT [ "/usr/sbin/apachectl" ]
CMD [ "-D", "FOREGROUND" ]

